type = "webpack"
account_id = "3811365464a8e56b2b27a5590e328e49"
workers_dev = true

[site]
bucket = "./build"
entry-point = "./scripts/workers-site"

[env.staging]
name = "audius-staging"
vars = { ENVIRONMENT = "staging", GA = "https://general-admission.staging.audius.co", SITEMAP = "http://staging.audius.co.s3-website-us-west-1.amazonaws.com" }

[env.staging-release]
name = "audius-staging-release-candidate"
vars = { ENVIRONMENT = "staging", GA = "https://general-admission.staging.audius.co", SITEMAP = "http://staging.audius.co.s3-website-us-west-1.amazonaws.com" }

[env.release]
name = "audius-release-candidate"
vars = { ENVIRONMENT = "production", GA = "https://general-admission.audius.co", SITEMAP = "http://audius.co.s3-website-us-west-1.amazonaws.com" }

[env.production]
name = "audius"
vars = { ENVIRONMENT = "production", GA = "https://general-admission.audius.co", SITEMAP = "http://audius.co.s3-website-us-west-1.amazonaws.com" }