version: '3'
services:
  db3:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_creator_node
    volumes:
      - postgres_data3:/var/lib/postgresql/data/
    ports:
      - '4452:5432'
  creator-node3:
    build: ../../.
    command: sh -c '/usr/bin/wait && exec ./node_modules/.bin/nodemon src/index.js | ./node_modules/.bin/bunyan'
    env_file:
      - ./development3.env
    depends_on:
      - db3
      - redis3
    ports:
      - '4020:4000'
    volumes:
      - file_storage3:/file_storage
      - '../..:/usr/src/app'
  redis3:
    image: redis:5.0.4
    ports:
      - '4399:6379'

volumes:
  postgres_data3:
  file_storage3:
