parameters:
  instance-name:
    description: Name of instance
    type: string
  create-instance-args:
    description: Extra arguments to use when creating instance
    type: string
    default: --preemptible --tags=circleci
  pass-env:
    description: Name of enviroinment variables to pass to instance (useful for passing secrets)
    type: string
    default: ''
  steps:
    description: Steps to run on GCP instance
    type: steps
    default: []
steps:
  - run:
      name: Create GCP instance
      command: |
        # Create firewall for instance
        CIRCLECI_IP=$(curl https://checkip.amazonaws.com)
        gcloud compute firewall-rules create "<< parameters.instance-name >>" \
          --source-ranges "$CIRCLECI_IP" \
          --action allow --rules tcp:22 \
          --target-tags "<< parameters.instance-name >>"

        # Create GCP instance
        gcloud compute instances create \
          "<< parameters.instance-name >>" \
          << parameters.create-instance-args >> \
          --tags "<< parameters.instance-name >>"

        while ! gcloud compute ssh "$INSTANCE_USER@<< parameters.instance-name >>" --command=true; do
          sleep 1
        done

        # Generate env file with env to pass to gcp instance
        touch /tmp/gcp-pass-env.sh
        for env in << parameters.pass-env >>; do
          printf "export %q=%q;" "$env" "$(printenv "$env")" >> /tmp/gcp-pass-env.sh
        done
        gcloud compute scp /tmp/gcp-pass-env.sh "$INSTANCE_USER@<< parameters.instance-name >>:/tmp/gcp-pass-env.sh"
        rm /tmp/gcp-pass-env.sh

        # Replace bash with executable that forwards commands to the instance
        mv /bin/bash /tmp/bash.real
        echo >/bin/bash '#!/tmp/bash.real
        gcloud compute ssh --quiet "$INSTANCE_USER@<< parameters.instance-name >>" --command="source /tmp/gcp-pass-env.sh; bash $(printf "%q " "$@")"'
        chmod +x /bin/bash
  - steps: << parameters.steps >>
  - run:
      name: Record Success
      shell: /tmp/bash.real
      command: touch /tmp/success
  # - run:
  #     name: Delete GCP resources
  #     when: always
  #     shell: /tmp/bash.real
  #     command: |
  #       gcloud compute instances delete --quiet "<< parameters.instance-name >>"
  #       gcloud compute firewall-rules delete --quiet "<< parameters.instance-name >>"

  #       mv /bin/bash /tmp/bash.deleted
  #       mv /tmp/bash.real /bin/bash
