version: '3'
services:
  creator-node-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_creator_node
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '${CREATOR_NODE_DB_HOST_PORT}:5432'
    networks:
      - audius_dev
  creator-node:
    build: ../.
    command: sh -c '/usr/bin/wait && exec ./scripts/dev-server.sh'
    depends_on:
      - creator-node-db
      - creator-node-redis
    environment:
      - redisHost=${COMPOSE_PROJECT_NAME}_creator-node-redis_1
      - dbUrl=postgres://postgres:postgres@${COMPOSE_PROJECT_NAME}_creator-node-db_1:5432/audius_creator_node
      - WAIT_HOSTS=${COMPOSE_PROJECT_NAME}_creator-node-db_1:5432, ${COMPOSE_PROJECT_NAME}_creator-node-redis_1:6379
      - port=${CREATOR_NODE_HOST_PORT}
      - spOwnerWalletIndex=${SP_OWNER_WALLET_INDEX}
      - delegateOwnerWallet=${delegateOwnerWallet}
      - delegatePrivateKey=${delegatePrivateKey}
      - creatorNodeEndpoint=${creatorNodeEndpoint}
      - manualSyncsDisabled=${manualSyncsDisabled}
      - devMode=${DEV_MODE}
      - spOwnerWallet=${spOwnerWallet}
      - isUserMetadataNode=${CREATOR_NODE_IS_USER_METADATA}
    env_file:
      - ./env/base.env
    ports:
      - '${CREATOR_NODE_HOST_PORT}:${CREATOR_NODE_HOST_PORT}'
    volumes:
      - ../file_storage:/file_storage
      - ..:/usr/src/app
      # Prevent hiding node_modules on container with host volume
      # From https://github.com/barrysteyn/node-scrypt/issues/148
      - /usr/src/app/node_modules
      # Mount audius libs as a directory
      - ../../libs:/usr/src/audius-libs
    networks:
      - audius_dev
  creator-node-redis:
    image: redis:5.0.4
    ports:
      - '${CREATOR_NODE_REDIS_HOST_PORT}:6379'
    networks:
      - audius_dev

volumes:
  postgres_data:
  file_storage:

networks:
  audius_dev:
    external: true