when: << pipeline.parameters.run-core-workflow >>
jobs:
  - push-docker-image:
      name: push-core
      context: [Vercel, dockerhub]
      service: core
      filters:
        branches:
          only: main

  - test:
      name: test-core
      context: Vercel
      service: core

  - deploy-stage-nodes-just-tag:
      service: core
      name: deploy-core-staging
      requires:
        - push-core
      filters:
        branches:
          only: main
      context: github
