when: << pipeline.parameters.run-harmony-workflow >>
jobs:
  # - harmony-init:
  #     context:
  #       - Vercel
  # - harmony-build-storybook:
  #     context:
  #       - Vercel
  #     requires:
  #       - harmony-init
  # - harmony-test-storybook:
  #     context:
  #       - Vercel
  #     requires:
  #       - harmony-build-storybook
  # - harmony-deploy-storybook:
  #     context: Audius Client
  #     requires:
  #       - harmony-build-storybook
  #     filters:
  #       branches:
  #         only: /^main$/
  # - harmony-deploy-chromatic:
  #     requires:
  #       - harmony-init
  #     filters:
  #       branches:
  #         ignore:
  #           - /^release.*$/
