root-publish-github-release-client:
  working_directory: ~/apps
  docker:
    - image: cibuilds/github:0.13
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: 'Publish Release on GitHub'
        command: |
          VERSION=$(jq -r .version ./package.json)
          CHANGELOG=$(git log --format=%B -n 1)
          ghr -t ${GHI_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "${CHANGELOG}" -soft client-v${VERSION} ./

root-publish-github-release-protocol:
  working_directory: ~/apps
  docker:
    - image: cibuilds/github:0.13
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: 'Publish Release on GitHub'
        command: |
          VERSION=$(jq -r .version ./packages/discovery-provider/.version.json)
          CHANGELOG=$(git log --format=%B -n 1)
          ghr -t ${GHI_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "${CHANGELOG}" -soft protocol-v${VERSION} ./
