# VPN setup from https://support.circleci.com/hc/en-us/articles/360049397051-How-To-Set-Up-a-VPN-Connection-During-Builds

parameters:
  hosts:
    description: 'Hosts to deploy to'
    type: string
  service:
    description: 'Service to deploy on hosts'
    type: string
  freeze:
    description: 'Whether to freeze and skip deploy'
    type: string
    default: 'false'
machine:
  image: ubuntu-2004:202201-02
steps:
  - when:
      condition:
        matches: { pattern: 'true', value: << parameters.freeze >> }
      steps:
        - run: circleci-agent step halt
  - run:
      name: Install OpenVPN
      command: |
        sudo apt-get update
        sudo apt-get install openvpn openvpn-systemd-resolved
  - run:
      name: Check IP before VPN connection
      command: |
        ip a
        echo "Public IP before VPN connection is $(curl checkip.amazonaws.com)"
  - run:
      name: VPN Setup
      background: true
      command: |
        echo $VPN_CLIENT_CONFIG | base64 --decode > /tmp/config.ovpn

        if grep -q auth-user-pass /tmp/config.ovpn; then
          if [ -z "${VPN_USER:-}" ] || [ -z "${VPN_PASSWORD:-}" ]; then
            echo "Your VPN client is configured with a user-locked profile. Make sure to set the VPN_USER and VPN_PASSWORD environment variables"
            exit 1
          else
            printf "$VPN_USER\\n$VPN_PASSWORD" > /tmp/vpn.login
          fi
        fi

        vpn_command=(sudo openvpn
          --config /tmp/config.ovpn
          --route 169.254.0.0 255.255.0.0 net_gateway
          --script-security 2
          --up /etc/openvpn/update-systemd-resolved --up-restart
          --down /etc/openvpn/update-systemd-resolved --down-pre
          --dhcp-option DOMAIN-ROUTE .)

        if grep -q auth-user-pass /tmp/config.ovpn; then
          vpn_command+=(--auth-user-pass /tmp/vpn.login)
        fi

        ET_phone_home=$(ss -Hnto state established '( sport = :ssh )' | head -n1 | awk '{ split($4, a, ":"); print a[1] }')
        echo $ET_phone_home

        if [ -n "$ET_phone_home" ]; then
          vpn_command+=(--route $ET_phone_home 255.255.255.255 net_gateway)
        fi

        for IP in $(host runner.circleci.com | awk '{ print $4; }')
          do
            vpn_command+=(--route $IP 255.255.255.255 net_gateway)
            echo $IP
        done

        for SYS_RES_DNS in $(systemd-resolve --status | grep 'DNS Servers'|awk '{print $3}')
          do
            vpn_command+=(--route $SYS_RES_DNS 255.255.255.255 net_gateway)
            echo $SYS_RES_DNS
        done

        "${vpn_command[@]}" > /tmp/openvpn.log
  - run:
      name: Wait for the connection to be established and check IP
      command: |
        counter=1
        until [ -f /tmp/openvpn.log ] && [ "$(grep -c "Initialization Sequence Completed" /tmp/openvpn.log)" != 0 ] || [ "$counter" -ge 15 ]; do
          ((counter++))
          echo "Attempting to connect to VPN server..."
          sleep 1;
        done

        if [ ! -f /tmp/openvpn.log ] || (! grep -iq "Initialization Sequence Completed" /tmp/openvpn.log); then
          printf "\nUnable to establish connection within the allocated time ---> Giving up.\n"
          exit 1
        else
          printf "\nVPN connected\n"
          printf "\nPublic IP is now %s\n" "$(curl -s http://checkip.amazonaws.com)"
        fi

  - add_ssh_keys:
      fingerprints:
        - 'df:1a:e3:9b:57:58:24:34:fb:aa:c1:b2:0b:ec:c8:42' # ~/.ssh/audius_infrastructure
        - 'd1:28:d4:5e:ca:d9:bb:70:06:da:e0:f0:00:7c:d4:a3' # ~/.ssh/google_compute_engine
        - 'd0:0b:a0:19:ac:46:58:e4:6c:ac:34:99:f6:1b:31:bb' # github.com

  - run:
      name: Configure SSH
      command: |
        git clone git@github.com:AudiusProject/audius-ssh.git audius-ssh
        sed "/AddKeysToAgent/d; /UseKeychain/d" audius-ssh/ssh_config >> ~/.ssh/config
  - run:
      name: Deploy
      command: |
        set -x
        hosts=(<< parameters.hosts >>)
        aggregated_messages=""

        for host in "${hosts[@]}"; do
          ssh "ubuntu@$host" -- audius-cli pull
          ssh "ubuntu@$host" -- audius-cli set-tag -y "$CIRCLE_SHA1"
          ssh "ubuntu@$host" -- audius-cli launch -y "<< parameters.service >>"

          healthy=false
          for retry in {1..100}; do
            echo "Retry: $retry"
            if ssh "ubuntu@$host" -- audius-cli health-check "<< parameters.service >>"; then
              healthy=true
              break
            fi
            sleep 10
          done

          if [[ "$healthy" == "false" ]]; then
            author=$(git log -n 1 --pretty=format:"%an <%ae>")
            message="Deploy ${host} failed, dirty changes from: ${author}"
            aggregated_messages="${aggregated_messages}${message}\n"
          fi
        done

        echo "Aggregated messages: $aggregated_messages"
        echo "export AGGREGATED_MESSAGES=\"$aggregated_messages\"" >> $BASH_ENV

  - run:
      name: Early exit if success
      command: |
        if [ -z "$AGGREGATE_MESSAGES" ]; then
          circleci-agent step halt
        fi

  - slack/notify:
      custom: |
        {
          "blocks": [
            {
              "type": "section",
              "text": {
                "text": "*Failed Deploy @ $CIRCLE_TAG*\n\n$AGGREGATED_MESSAGES"
                "type": "mrkdwn"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "View Job"
                },
                "url": "$CIRCLE_BUILD_URL"
              }
            }
          ]
        }
