parameters:
  service:
    description: 'Service to deploy (creator-node, discovery-provider, identity-service, ddex)'
    type: string
resource_class: small
docker:
  - image: cimg/base:2023.01
steps:
  - gh/setup:
      version: 2.23.0
  - add_ssh_keys:
      fingerprints:
        - "d0:0b:a0:19:ac:46:58:e4:6c:ac:34:99:f6:1b:31:bb" # github.com
  - run:
      name: Add github.com to known_hosts
      command: |
        echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
  - run:
      name: Set git config
      command: |
        git config --global user.email "audius-infra@audius.co"
        git config --global user.name "audius-infra"
  - run:
      name: Update tag in audius-docker-compose stage branch
      command: |
        git clone --branch stage https://github.com/AudiusProject/audius-docker-compose.git audius-docker-compose
        cd audius-docker-compose
        sed -i "s/\({TAG:-\)[^}]*\}/\1$CIRCLE_SHA1}/" << parameters.service >>/docker-compose*.yml
        git add */docker-compose*.yml
        git commit -m "Update tag to $CIRCLE_SHA1 for << parameters.service >>"
        git push origin stage
  - run:
      name: Wait for 2 minutes for staging nodes to auto-upgrade
      command: sleep 120
