resource_class: small
docker:
  - image: google/cloud-sdk:412.0.0-slim
steps:
  - gcp-auth
  - run:
      name: Cleanup Instances
      command: |
        old_instances=$(gcloud compute instances list --format="csv(name)[no-heading]" --filter="creationTimestamp < -P1H AND name~'circleci-.*'" --sort-by=creationTimestamp)
        if [[ "$old_instances" != "" ]]; then
          echo "Deleting instances:" $old_instances
          gcloud compute instances delete --quiet $old_instances
        fi
  - run:
      name: Cleanup Images
      command: |
        old_images=$(gcloud compute images list --format="csv(name)[no-heading]" --filter="creationTimestamp < -P3D AND name~'audius-protocol-.*'" --sort-by=creationTimestamp)
        if [[ "$old_images" != "" ]]; then
          echo "Deleting images:" $old_images
          gcloud compute images delete --quiet $old_images
        fi
  - run:
      name: Cleanup Firewall Rules
      command: |
        old_firewalls=$(gcloud compute firewall-rules list --format="csv(name)[no-heading]" --filter="creationTimestamp < -P1H AND name~'circleci-.*'" --sort-by=creationTimestamp)
        if [[ "$old_images" != "" ]]; then
          echo "Deleting firewalls:" $old_firewalls
          gcloud compute firewall-rules delete --quiet $old_firewalls
        fi
