web-init:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - dependency-cache-{{ checksum "packages/web/package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-

    - run: rm -rf /home/circleci/audius-client/packages/web/node_modules/websocket/.git

    - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc

    - run: |
        npm ci

    - save_cache:
        key: dependency-cache-{{ checksum "packages/web/package-lock.json" }}
        paths:
          - ./packages/web/node_modules

    # Lint
    - run:
        name: lint
        command: |
          cd packages/web
          npm run lint

    # Run tests
    - run:
        name: test
        command: |
          cd packages/web
          npm test

    # Persist the build directory to a workspace
    - persist_to_workspace:
        root: ./
        paths:
          - packages/web/node_modules
          - packages/stems/node_modules
          - packages/stems/dist

web-build-demo:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  resource_class: xlarge
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: build-demo
        # Set the branch name as the PUBLIC_URL so that relative paths work, e.g.
        # demo.audius.co/some-branch/handle/track resolves as /handle/track would at audius.co
        command: |
          cd packages/web
          export PUBLIC_URL=/${CIRCLE_BRANCH}
          CI=false npm run build:stage
          mv build-staging build-demo
    - persist_to_workspace:
        root: ./
        paths:
          - packages/web/build-demo

web-build-staging:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  resource_class: xlarge
  steps:
    - web-build:
        build-type: stage
        build-directory: packages/web/build-staging
        build-name: build-staging

web-build-ipfs-staging:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  resource_class: xlarge
  steps:
    - web-build:
        build-type: ipfs-stage
        build-directory: packages/web/build-ipfs-staging
        build-name: build-ipfs-staging
    - run:
        name: zip build-ipfs-staging
        command: |
          cd packages/web
          zip -r build-ipfs-staging.zip ./build-ipfs-staging
    - persist_to_workspace:
        root: ./
        paths:
          - packages/web/build-ipfs-staging.zip

web-test-staging:
  working_directory: ~/
  docker:
    - image: circleci/node:14.18-browsers
  resource_class: large
  steps:
    - run:
        name: download probers
        command: |
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          echo $'Host github.com\n\tStrictHostKeyChecking no' > ~/.ssh/config
          git clone git@github.com:AudiusProject/probers.git
          cd probers
    # Download and cache dependencies
    - restore_cache:
        keys:
          - probers-dependency-cache-{{ checksum "probers/package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - probers-dependency-cache-
    - run:
        name: install probers dependencies
        command: |
          cd probers
          npm ci
    - save_cache:
        key: probers-dependency-cache-{{ checksum "probers/package-lock.json" }}
        paths:
          - ./probers/node_modules
    - attach_workspace:
        at: ./
    - run:
        name: serve and run prober tests
        command: |
          npm install serve
          node node_modules/serve/bin/serve.js -l 3001 -s packages/web/build-staging &
          cd probers
          npm run test:ci

web-build-production:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  resource_class: xlarge
  steps:
    - web-build:
        build-type: prod-source-maps
        build-directory: packages/web/build-production
        build-name: build-production

web-build-ipfs-production:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  resource_class: xlarge
  steps:
    - web-build:
        build-type: ipfs-prod
        build-directory: packages/web/build-ipfs-production
        build-name: build-ipfs-production
    - run:
        name: zip build
        command: |
          cd packages/web
          zip -r build-ipfs-production.zip ./build-ipfs-production
    - persist_to_workspace:
        root: ./
        paths:
          - packages/web/build-ipfs-production.zip

web-deploy-demo:
  working_directory: ~/audius-client
  docker:
    - image: circleci/python:2.7-jessie
  steps:
    - checkout
    - web-install-awscli
    - attach_workspace:
        at: ./
    - run:
        name: Deploy to S3
        command: aws s3 sync packages/web/build-demo s3://frontend-demo.audius.co/${CIRCLE_BRANCH} --delete --cache-control max-age=0
    - web-pr-comment:
        comment: Preview this change https://demo.audius.co/${CIRCLE_BRANCH}

web-deploy-staging-s3:
  working_directory: ~/audius-client
  docker:
    - image: circleci/python:2.7-jessie
  steps:
    - checkout
    - web-install-awscli
    - attach_workspace:
        at: ./
    - run:
        name: Create TAR
        command: |
          tar -zcvf packages/web/build-staging.tar.gz packages/web/build-staging
    - run:
        name: Deploy to S3
        command: |
          aws s3 sync --exclude "packages/web/sitemaps/*" packages/web/build-staging s3://staging.audius.co --delete --cache-control max-age=0
          aws s3 cp packages/web/build-staging.tar.gz s3://staging.audius.co/build-staging.tar.gz --cache-control max-age=0 --content-type 'application/json' --metadata-directive REPLACE

web-deploy-staging-cloudflare:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - web-deploy-cloudflare:
        build-type: staging
        environment: staging
        copy-robots: false

web-deploy-ipfs-staging:
  working_directory: ~/audius-client
  docker:
    - image: circleci/python:2.7-jessie
  steps:
    - web-deploy-ipfs:
        build-type: staging

web-update-staging-ga-ipfs-build:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - web-update-ga-ipfs-build:
        build-type: stage

web-publish-staging-build-cids:
  working_directory: ~/audius-client
  docker:
    - image: circleci/python:2.7-jessie
  steps:
    - web-publish-build-cids:
        build-type: staging

web-update-ipfs-staging-records:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - web-update-ipfs-records:
        dns-name: _dnslink.ipfs.staging.audius.co
        dns-id: "${CLOUDFLARE_STAGE_SITE_IPFS_DNS_ID}"

web-deploy-release-candidate:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - web-deploy-cloudflare:
        build-type: production
        environment: release
        copy-robots: true

web-deploy-production-s3:
  working_directory: ~/audius-client
  docker:
    - image: circleci/python:2.7-jessie
  steps:
    - checkout
    - web-install-awscli
    - attach_workspace:
        at: ./
    - run:
        name: Create TAR
        command: |
          tar -zcvf packages/web/build-production.tar.gz packages/web/build-production
    - run:
        name: Deploy to S3
        # Deploy, but exclude sourcemaps
        command: |
          aws s3 sync --exclude "*.map" --exclude robots.txt --exclude "packages/web/sitemaps/*" packages/web/build-production s3://audius.co --delete --cache-control max-age=604800
          aws s3 cp s3://audius.co/index.html s3://audius.co/index.html --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --metadata-directive REPLACE --acl public-read
          aws s3 cp packages/web/robots.txt s3://audius.co --cache-control max-age=0 --content-type 'application/json' --metadata-directive REPLACE
          aws s3 cp packages/web/build-production.tar.gz s3://audius.co/build-production.tar.gz --cache-control max-age=0 --content-type 'application/json' --metadata-directive REPLACE
    - run:
        name: Invalidate cache
        # Note: cache invalidation is charged per path, so this only counts as 1/1000 monthly quota.
        command: aws cloudfront create-invalidation --distribution-id E1ZJ9Z971FJQJ8 --paths "/*"

web-deploy-production-cloudflare:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - web-deploy-cloudflare:
        build-type: production
        environment: production
        copy-robots: true

web-deploy-ipfs-production:
  working_directory: ~/audius-client
  docker:
    - image: circleci/python:2.7-jessie
  steps:
    - web-deploy-ipfs:
        build-type: production

web-update-production-ga-ipfs-build:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - web-update-ga-ipfs-build:
        build-type: prod

web-publish-production-build-cids:
  working_directory: ~/audius-client
  docker:
    - image: circleci/python:2.7-jessie
  steps:
    - web-publish-build-cids:
        build-type: production

web-update-ipfs-production-records:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - web-update-ipfs-records:
        dns-name: _dnslink.ipfs.audius.co
        dns-id: "${CLOUDFLARE_PROD_SITE_IPFS_DNS_ID}"

web-deploy-sentry-sourcemaps:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: install-sentry-cli
        command: |
          cd packages/web
          npm install @sentry/cli
    - run:
        name: cut-sentry-release
        command: |
          cd packages/web
          node_modules/.bin/sentry-cli --auth-token ${SENTRY_AUTH_TOKEN} releases --org audius --project audius-client new ${CIRCLE_SHA1}
    - run:
        name: upload-sourcemaps
        command: |
          cd packages/web
          node_modules/.bin/sentry-cli --auth-token ${SENTRY_AUTH_TOKEN} releases --org audius --project audius-client files ${CIRCLE_SHA1} upload-sourcemaps --no-rewrite build-production
    - run:
        name: finalize-release
        command: |
          cd packages/web
          node_modules/.bin/sentry-cli --auth-token ${SENTRY_AUTH_TOKEN} releases --org audius --project audius-client finalize ${CIRCLE_SHA1}

web-dist-mac-staging:
  working_directory: ~/audius-client
  macos: # Run on osx so dmg can be created and signed.
    xcode: "13.3.0"
  steps:
    - web-distribute:
        build-type: mac-publish

web-dist-win-staging:
  working_directory: ~/audius-client
  docker:
    - image: electronuserland/builder:wine-mono
  steps:
    - web-distribute:
        build-type: win-publish

web-dist-linux-staging:
  working_directory: ~/audius-client
  docker:
    - image: electronuserland/builder
  steps:
    - web-distribute:
        build-type: linux-publish

web-dist-mac-production:
  working_directory: ~/audius-client
  macos: # Run on osx so dmg can be created and signed.
    xcode: "13.3.0"
  steps:
    - web-distribute:
        build-type: mac-publish-production

web-dist-win-production:
  working_directory: ~/audius-client
  docker:
    - image: electronuserland/builder:wine-mono
  steps:
    - web-distribute:
        build-type: win-publish-production

web-dist-linux-production:
  working_directory: ~/audius-client
  docker:
    - image: electronuserland/builder
  steps:
    - web-distribute:
        build-type: linux-publish-production
