# Compose file to run the discovery redis container
version: '3'
services:
  redis-server:
    image: redis:3.0-alpine
    command: redis-server --save '' 
    ports:
      - '${audius_redis_port}:6379'
    networks:
      - audius_dev

networks:
  audius_dev:
    external: true