publisher:
  address: 9pasZKEQoJtKBECQ7W6jdanaFnan4pzCL2DZiChnteQi
  name: Audius
  website: https://audius.co
  email: contact@audius.co
  media:
    - purpose: icon
      uri: ./media/publisher_icon.png
app:
  address: CpGnQL2UZHbvFCuquTvRjsUomwTgXZp4wA1axYJtzf5i
  name: Audius Music
  android_package: co.audius.app
  urls:
    license_url: https://audius.co/legal/terms-of-use
    copyright_url: https://audius.co/legal/terms-of-use
    privacy_policy_url: https://audius.co/legal/privacy-policy
    website: https://audius.co
  media:
    - purpose: icon
      uri: ./media/app_icon.png
release:
  address: EPgeXWzqQRQryvSMNu55JijGsCnwmh2WeveDqV1htRL5
  media:
    - purpose: icon
      uri: ./media/publisher_icon.png
    - purpose: screenshot
      uri: ./media/screenshot1.png
    - purpose: screenshot
      uri: ./media/screenshot2.png
    - purpose: screenshot
      uri: ./media/screenshot3.png
    - purpose: screenshot
      uri: ./media/screenshot4.png
    - purpose: screenshot
      uri: ./media/screenshot5.png
    - purpose: screenshot
      uri: ./media/screenshot6.png
  files:
    - purpose: install
      uri: ../android/app/build/outputs/apk/prod/release/app-prod-release.apk
  catalog:
    en-US:
      name: Audius Music
      short_description: Discover & stream new artists
      long_description: |-
        We give everyone the freedom to share & listen. Audius is a brand-new streaming platform built for all musicians, not just those signed to labels. Build a fanbase, share your works in progress, and then publish your completed tracks for all the world to hear. Create, grow, and monetize, all without the need to graduate off the platform or sign a record deal.
        Out of the box, Audius includes: High Quality Audio (Streaming at 320kbps), Free Forever (Unlimited uploads and listening at no cost)
      new_in_version: 'Audius is always improving! Keep Updates on to make sure you don''t miss new features and improvements. In this version: Bug fixes, Stability improvements'
      saga_features: Connect Solana Mobile wallets directly to Audius to unlock additional features
solana_mobile_dapp_publisher_portal:
  testing_instructions: Please log in as any Audius account, e.g. solanamobile@audius.co. Visit the $AUDIO & Rewards tab in the UI to connect a wallet. Connect a wallet by choosing the wallet picker, selecting Solana Mobile, and following the connect wallet & sign messages flows. Upon returning to the Audius app, your wallet should be connected and corresponding collectibles and token balances can be used to interact with unlockable Audius features.
lastSubmittedVersionOnChain:
  address: EPgeXWzqQRQryvSMNu55JijGsCnwmh2WeveDqV1htRL5
  version_code: 732
  apk_hash: c62Z/M9dArmisI3hSC2oOMXEsyXvpK7OTyNzRrf4qLI=
lastUpdatedVersionOnStore:
  address: EPgeXWzqQRQryvSMNu55JijGsCnwmh2WeveDqV1htRL5
