stems-init:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - checkout

    - create_concatenated_package_lock:
        filename: combined-package-lock.txt

    - restore_cache:
        keys:
          - cache-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}

    - run:
        name: Link packages
        command: |
          npm run link

    # Lint
    - run:
        name: lint
        command: |
          cd packages/stems
          npm run lint

    # Persist node modules directory to workspace
    - persist_to_workspace:
        root: ./
        paths:
          - packages/stems/node_modules

stems-build-storybook:
  working_directory: ~/stems
  docker:
    - image: circleci/node:14.18
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: build storybook
        command: |
          cd packages/stems
          npm run build-storybook
    - persist_to_workspace:
        root: ./
        paths:
          - packages/stems/storybook-static

stems-deploy-storybook:
  working_directory: ~/stems
  docker:
    - image: circleci/node:14.18
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: install wrangler
        command: |
          cd packages/stems
          npm install @cloudflare/wrangler
    - run:
        name: Set up workers site
        command: |
          cd packages/stems/scripts/workers-site
          npm i
    - run:
        name: Deploy to Cloudflare
        command: |
          cd packages/stems
          npx wrangler publish
