version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_creator_node
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '4432:5432'
  creator-node:
    build: ../.
    command: sh -c '/usr/bin/wait && exec ./node_modules/.bin/nodemon src/index.js | ./node_modules/.bin/bunyan'
    env_file:
      - ./development.env
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'
    volumes:
      - file_storage:/file_storage
      # Mount the code for hot reloading
      - ..:/usr/src/app
      # Prevent hiding node_modules on container with host volume
      # From https://github.com/barrysteyn/node-scrypt/issues/148
      - /usr/src/app/node_modules # does fresh reinstsall of deps
  redis:
    image: redis:5.0.4
    ports:
      - '4379:6379'

volumes:
  postgres_data:
  file_storage:
