version: "3.9"

x-comms-environment: &comms-environment
  AUDIUS_REBALANCE_INTERVAL_HOURS: "0.005" # check for unhealthy nodes and update healthy node set every 18 seconds
  AUDIUS_HEALTH_TTL_HOURS: "0.005" # consider a node unhealthy if it hasn't self-reported "OK" status in the last 18 seconds
  AUDIUS_REPORT_OK_INTERVAL_SECONDS: 4
  AUDIUS_SHARD_LENGTH: 1
  AUDIUS_DEV_ONLY_REGISTERED_NODES: ' [ { "id": "content-node::1", "spId": "1", "endpoint": "http://audius-protocol-storage-1", "delegateOwnerWallet": "0x1c185053c2259f72fd023ED89B9b3EBbD841DA0F", "owner": { "id": "0x339511506f7BfB5f5d7042b450B9D450626dbB91" }, "type": { "id": "content-node" } }, { "id": "content-node::2", "spId": "2", "endpoint": "http://audius-protocol-storage-2", "delegateOwnerWallet": "0x90b8d2655A7C268d0fA31758A714e583AE54489D", "owner": { "id": "0x11327A21bc4dE71a1274D7C1e2c94D50AdeeBB88" }, "type": { "id": "content-node" } }, { "id": "content-node::3", "spId": "3", "endpoint": "http://audius-protocol-storage-3", "delegateOwnerWallet": "0xb7b9599EeB2FD9237C94cFf02d74368Bb2df959B", "owner": { "id": "0x339511506f7BfB5f5d7042b450B9D450626dbB91" }, "type": { "id": "content-node" } }, { "id": "content-node::4", "spId": "4", "endpoint": "http://audius-protocol-storage-4", "delegateOwnerWallet": "0xfa4f42633Cb0c72Aa35D3D1A3566abb7142c7b16", "owner": { "id": "0x11327A21bc4dE71a1274D7C1e2c94D50AdeeBB88" }, "type": { "id": "content-node" } }, { "id": "discovery-node::1", "spId": "5", "endpoint": "http://audius-protocol-comms-discovery-1", "delegateOwnerWallet": "0x123d0813710D55A9C38A2D7BC502Ff00A1a0279e", "owner": { "id": "0x339511506f7BfB5f5d7042b450B9D450626dbB91" }, "type": { "id": "discovery-node" } }, { "id": "discovery-node::2", "spId": "6", "endpoint": "http://audius-protocol-comms-discovery-2", "delegateOwnerWallet": "0x9262c9A1b172fF2A9C027B55862389d00b68A26a", "owner": { "id": "0x11327A21bc4dE71a1274D7C1e2c94D50AdeeBB88" }, "type": { "id": "discovery-node" } }, { "id": "discovery-node::3", "spId": "7", "endpoint": "http://audius-protocol-comms-discovery-3", "delegateOwnerWallet": "0xBc2550Ae74fbbDF4eC30A8E65dd845a5a8510eb4", "owner": { "id": "0x339511506f7BfB5f5d7042b450B9D450626dbB91" }, "type": { "id": "discovery-node" } } ]'

x-discovery: &discovery
  build:
    context: ${PROJECT_ROOT}/comms
    dockerfile: Dockerfile
    target: builder
    args:
      GOARCH: arm64
  restart: unless-stopped
  # command: 'comms discovery'
  stop_signal: SIGKILL
  volumes:
    - ${PROJECT_ROOT}/comms/discovery:/app/discovery
    - ${PROJECT_ROOT}/comms/shared:/app/shared
  depends_on:
    db:
      condition: service_started
  profiles:
    - not_comms

services:
  # DISCOVERY (comms, not a full discovery provider)

  comms-discovery-1:
    container_name: audius-protocol-comms-discovery-1
    <<: *discovery
    environment:
      <<: *comms-environment
      audius_db_url: "postgresql://postgres:postgres@db:5432/com1?sslmode=disable"
      audius_delegate_private_key: "c82ad757622db5a148089e0a8fc1741cefa8677ab56a2ac9e38dac905c5ad7c7" # Public key: "0x123d0813710D55A9C38A2D7BC502Ff00A1a0279e"

  comms-discovery-2:
    container_name: audius-protocol-comms-discovery-2
    <<: *discovery
    environment:
      <<: *comms-environment
      audius_db_url: "postgresql://postgres:postgres@db:5432/com1?sslmode=disable"
      audius_delegate_private_key: "d2b12371a062b73ce665288f894844ab75760d0ed0c580ff19d21b54d260ceb2" # Public key: "0x9262c9A1b172fF2A9C027B55862389d00b68A26a"

  comms-discovery-3:
    container_name: audius-protocol-comms-discovery-3
    <<: *discovery
    environment:
      <<: *comms-environment
      audius_db_url: "postgresql://postgres:postgres@db:5432/com1?sslmode=disable"
      audius_delegate_private_key: "6569932dff9fbe7c04382f87ac7098f90e7aa5cb0fe636b4e5c3cb4e30668812" # Public key: "0xBc2550Ae74fbbDF4eC30A8E65dd845a5a8510eb4"

  # TEST

  comms-test:
    container_name: comms-test
    build:
      context: ${PROJECT_ROOT}/comms
      dockerfile: Dockerfile
      target: builder
      args:
        GOARCH: arm64
    environment:
      <<: *comms-environment
      audius_delegate_private_key: "293589cdf207ed2f2253bb72b17bb7f2cfe399cdc34712b1d32908d969682238" # Public key: "0x1c185053c2259f72fd023ED89B9b3EBbD841DA0F"
      AUDIUS_TEST_HOST: "audius-protocol-nats-storage-1"
      audius_db_url: "postgresql://postgres:postgres@db:5432/comms_test?sslmode=disable"
    # command: sh -c 'sleep 1s'
    volumes:
      - ${PROJECT_ROOT}/comms/:/app
    depends_on:
      ingress:
        condition: service_started
      db:
        condition: service_started
      comms-discovery-1:
        condition: service_started
      comms-discovery-2:
        condition: service_started
      comms-discovery-3:
        condition: service_started
    profiles:
      - not_comms
